#ifndef SCINTILLA_CONSTS_H
#define SCINTILLA_CONSTS_H

const SCI_GETFIRSTVISIBLELINE = 2152
const SCI_GETLINECOUNT = 2154
const SCI_GETLINE = 2153
const SCI_LINELENGTH = 2350
const SCI_LINEFROMPOSITION = 2166
const SCI_POSITIONFROMLINE = 2167
const SCI_GETCURRENTPOS = 2008
const SCI_SETEMPTYSELECTION = 2556
const SCI_GETLINEENDPOSITION = 2136
const SCI_POINTXFROMPOSITION = 2164
const SCI_POINTYFROMPOSITION = 2165
const SCI_TEXTHEIGHT = 2279
const SCI_DOCLINEFROMVISIBLE = 2221
const SCI_EOLANNOTATIONSETTEXT = 2740
const SCI_EOLANNOTATIONGETTEXT = 2741
const SCI_EOLANNOTATIONSETSTYLE = 2742
const SCI_EOLANNOTATIONCLEARALL = 2744
const SCI_EOLANNOTATIONSETVISIBLE = 2745
const SCI_EOLANNOTATIONSETSTYLEOFFSET = 2747
const SCI_EOLANNOTATIONGETSTYLEOFFSET = 2748
const SCI_STYLESETFORE = 2051
const SCI_STYLEGETFORE = 2481
const SCI_ALLOCATEEXTENDEDSTYLES = 2553
const SCI_GETMODEVENTMASK = 2378
const SCI_SETMODEVENTMASK = 2359

const SCN_DOUBLECLICK = 2006
const SCN_MODIFIED = 2008

const SC_MOD_INSERTTEXT = &h1
const SC_MOD_DELETETEXT = &h2
const SC_MOD_TEXT_FLAGS = (SC_MOD_INSERTTEXT or SC_MOD_DELETETEXT)

#endif
